site_name: Axe Programming Language
repo_url: https://github.com/axelang/axe
theme:
  name: material
  logo: assets/axe-2.png
  palette:
    primary: black

nav:
  - Home: index.md
  - Getting Started: getting_started.md
  - Installation: installation.md
  - Primitive Types: types.md
  - Standard Library:
    - std/arena: stdlib/arena.md
    - std/csv: stdlib/csv.md
    - std/errors: stdlib/errors.md
    - std/string: stdlib/string.md
    - std/memory: stdlib/memory.md
    - std/io: stdlib/io.md
    - std/math: stdlib/math.md
    - std/net: stdlib/net.md
    - std/time: stdlib/time.md
    - std/term: stdlib/term.md
    - std/regex: stdlib/regex.md
    - std/typecons: stdlib/typecons.md
    - std/lists: stdlib/lists.md
    - std/json: stdlib/json.md
    - std/crypto: stdlib/crypto.md
    - std/random: stdlib/random.md
    - std/uuid: stdlib/uuid.md
    - std/os: stdlib/os.md
  - Language Features:
    - Modules: features/modules.md
    - Generics: features/generics.md
    - Error Handling: features/error_handling.md
    - Concurrency and Parallelism: features/concurrency.md
    - Macros: features/macros.md
    - Pattern Matching: features/pattern_matching.md
