site_name: Axe Programming Language
repo_url: https://github.com/axelang/axe
theme:
  name: material
  logo: assets/axe-2.png
  palette:
    primary: black
  features:
    - content.code.copy
nav:
  - Home: index.md
  - Getting Started: getting_started.md
  - Types:
    - Primitive Types: types.md
    - Foreign Types: features/foreign_types.md
    - Opaque Types: features/opaque_types.md
  - Standard Library:
    - std.algorithms: stdlib/algorithms.md
    - std.arena: stdlib/arena.md
    - std.csv: stdlib/csv.md
    - std.errors: stdlib/errors.md
    - std.string: stdlib/string.md
    - std.memory: stdlib/memory.md
    - std.io: stdlib/io.md
    - std.math: stdlib/math.md
    - std.maps: stdlib/maps.md
    - std.net: stdlib/net.md
    - std.parallelism: stdlib/parallelism.md
    - std.time: stdlib/time.md
    - std.term: stdlib/term.md
    - std.regex: stdlib/regex.md
    - std.typecons: stdlib/typecons.md
    - std.lists: stdlib/lists.md
    - std.json: stdlib/json.md
    - std.crypto: stdlib/crypto.md
    - std.random: stdlib/random.md
    - std.uuid: stdlib/uuid.md
    - std.os: stdlib/os.md
  - Control Flow: features/control_flow.md
  - Modules: features/modules.md
  - String Handling: features/strings.md
  - Lists: features/lists.md
  - Function Call Conventions: features/function_calls.md
  - Extern Functions: features/extern_functions.md
  - Error Handling: features/error_handling.md
  - Concurrency and Parallelism: features/concurrency.md
  - Macros: features/macros.md
  - Generics: features/generics.md
  - Overloads: features/overloads.md
  - Unsafe Blocks: features/unsafe.md
  - Memory Management: features/memory_management.md
  - Pointers:
    - Dereferencing: features/dereferencing.md
    - Taking Addresses: features/taking_addresses.md
  - Tooling:
    - Saw CLI: tooling/saw_cli.md
    - Axels: tooling/axels.md
    - Axedoc: tooling/axedoc.md

markdown_extensions:
  - pymdownx.highlight:
      use_pygments: false
  - pymdownx.superfences

extra_javascript:
  - https://cdnjs.cloudflare.com/ajax/libs/highlight.js/11.8.0/highlight.min.js
  - js/axe.js
  - js/hljs-init.js

extra_css:
  - https://cdnjs.cloudflare.com/ajax/libs/highlight.js/11.8.0/styles/github.min.css